### ISSUE TITLE
trigonometry function is not considered in <mo> tag

### ISSUE THREAD

**Issue by michjk** [Code-ReaQtor/latex2mathml#3] opened 2016-12-26 05:16 UTC
When I try to input latex for trigonometry function like \sin x, the "sin" is considered inside <mi> rather than inside <mo>.

**Comment by Code-ReaQtor** [comment] 2016-12-27 07:38
Sorry the issue is not clear to me. Can you cite an example?

**Comment by michjk** [comment] 2016-12-27 12:11
let say the latex is '\sin x' or '\sin {x}'
The result from latex2mathml is
`<math>
    <mrow>
        <mi>sin</mi>
        <mi>x</mi>
    </mrow>
</math>`

However I should be:
`<math>
    <mrow>
        <mo>sin</mo>
        <mi>x</mi>
    </mrow>
</math>`

since sin is a function, not an identifier

**Comment by Code-ReaQtor** [comment] 2016-12-27 13:36
All of my references use <mi> tag for _sin_ (and other identities).
- [mathtoweb](https://www.mathtowebonline.com/)
- [cheat-sheets](http://www.cheat-sheets.org/sites/mathml.su/english/index.xhtml)
- etc.

Even popular libraries like MathJax uses <mi> tag.
I'll start looking for solid references.

**Comment by Code-ReaQtor** [comment] 2017-01-03 11:31
@michjk Closing this issue until we find a solid reference.
Thanks! :)

**Closed by Code-ReaQtor** 2017-01-03 11:31 UTC
